[tool.semantic_release]
tag_format = "v{version}"
allow_zero_version = true
version_variables = [
    "manifest.json:version"
]

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
output_format = "md"

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.remote]
token_env = "GH_TOKEN"

[tool.semantic_release.commit_message]
template = "chore: release {version} [skip ci]"
